CREATE TABLE [施設] (
  [施設ID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [施設論理ID] LONG,
  [事業者ID] LONG,
  [表示順] LONG,
  [施設種別ID] LONG,
  [設置場所] VARCHAR (255),
  [許可対象区分ID] LONG,
  [許可番号形式ID] LONG,
  [許可番号] VARCHAR (255),
  [許可年月日] DATETIME,
  [設置年月日] DATETIME,
  [休止年月日] DATETIME,
  [再開年月日] DATETIME,
  [廃止年月日] DATETIME,
  [取消年月日] DATETIME,
  [取消理由] VARCHAR (200),
  [廃止理由] VARCHAR (500),
  [廃止確認日] DATETIME,
  [休止理由] VARCHAR (500),
  [一般廃棄物取扱フラグ] BIT,
  [産業廃棄物取扱フラグ] BIT,
  [処理方法ID] LONG,
  [設置形態区分ID] LONG,
  [容量m3] LONG,
  [面積m2] LONG,
  [管理区分ID] LONG,
  [埋立終了年月日] DATETIME,
  [保管施設面積m2] LONG,
  [保管量上限m3] LONG,
  [保管高さm] LONG,
  [有効開始日時] DATETIME,
  [有効終了日時] DATETIME
)
