CREATE TABLE [施設概要] (
  [履歴ID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [施設種別ID] LONG,
  [設置場所] VARCHAR (200),
  [許可対象区分ID] LONG,
  [許可番号形式ID] LONG,
  [許可番号] LONG,
  [許可年月日] DATETIME,
  [設置年月日] DATETIME,
  [休止年月日] DATETIME,
  [再開年月日] DATETIME,
  [廃止年月日] DATETIME,
  [取消年月日] DATETIME,
  [一般廃棄物取扱フラグ] BIT,
  [産業廃棄物取扱フラグ] BIT,
  [処理方法ID] LONG,
  [設置形態区分ID] LONG,
  [容量m3] DOUBLE,
  [面積m2] DOUBLE,
  [管理区分ID] LONG,
  [埋立終了年月日] DATETIME,
  [保管施設面積m2] DOUBLE,
  [保管量上限m3] DOUBLE,
  [保管高さm] DOUBLE
)
